//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TotalModel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carton
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Carton()
        {
            this.Cartons1 = new HashSet<Carton>();
            this.GoodsReceiptDetails = new HashSet<GoodsReceiptDetail>();
            this.Packs = new HashSet<Pack>();
            this.PickupDetails = new HashSet<PickupDetail>();
        }
    
        public int CartonID { get; set; }
        public int FillingCartonID { get; set; }
        public Nullable<int> AncestorCartonID { get; set; }
        public System.DateTime EntryDate { get; set; }
        public int FillingLineID { get; set; }
        public int CommodityID { get; set; }
        public Nullable<int> PalletID { get; set; }
        public int LocationID { get; set; }
        public string PCID { get; set; }
        public string Code { get; set; }
        public int EntryStatusID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Carton> Cartons1 { get; set; }
        public virtual Carton Carton1 { get; set; }
        public virtual Commodity Commodity { get; set; }
        public virtual FillingLine FillingLine { get; set; }
        public virtual Pallet Pallet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GoodsReceiptDetail> GoodsReceiptDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pack> Packs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PickupDetail> PickupDetails { get; set; }
    }
}
